const actions = {
  LOAD_MOVIES: "LOAD_MOVIES",
  LOAD_NEXT_PAGE: "LOAD_NEXT_PAGE",
  LOAD_GENRES: "LOAD_GENRES",
  LOAD_MOVIE: "LOAD_MOVIE",
  LOAD_CREDITS: "LOAD_CREDITS",
  SET_QUERY: "SET_QUERY",
  CLEAR_STATE: "CLEAR_STATE"
};

const modes = {
  POPULAR: "POPULAR",
  SEARCH: "SEARCH"
};

export { actions, modes };
